#!/bin/bash
set -euo pipefail
set -x
# This script cross‑compiles a custom (double precision, Mono-enabled) Godot
# Windows editor + export templates from Linux using MinGW, then builds the
# C# assemblies and gathers all artifacts (binaries, glue code, local NuGet feed).

# Resolve repo root (directory containing this script) and key paths.
REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$REPO_ROOT/eng/godot"             # Upstream / patched Godot source tree.
WORK_DIR="$HOME/tmp/godot_build"           # Throw‑away staging build directory.
DEST_DIR="$REPO_ROOT/eng/godot_artifacts"  # Final destination for build artifacts.
LOCAL_NUGET="$DEST_DIR/nuget_local" # Local NuGet feed to publish GodotSharp packages.

# Enable SCons compilation cache to speed up incremental builds across runs.
export SCONS_CACHE="${HOME}/.cache/scons"
export SCONS_CACHE_LIMIT=4096           # Cache size limit in MB.
mkdir -p "$SCONS_CACHE"

# Fail early if required tools are missing.
command -v scons >/dev/null
command -v dotnet >/dev/null
command -v x86_64-w64-mingw32-gcc >/dev/null || {
  echo "Missing mingw-w64 toolchain (x86_64-w64-mingw32-gcc). Install it."
  exit 1
}

# Optional deep clean of the Godot source tree (danger: removes untracked files).
if [[ "${CLEAN_SOURCE:-0}" == "1" ]]; then
  ( cd "$SRC_DIR" && git clean -xdf )
fi

# Start from a fresh isolated work directory to avoid polluting the source tree.
rm -rf "$WORK_DIR"
rm -rf "$DEST_DIR"
mkdir -p "$WORK_DIR"
mkdir -p "$DEST_DIR"

# Copy the Godot source into the isolated work area (keeps original tree pristine).
cp -r "$SRC_DIR" "$WORK_DIR/godot"
cd "$WORK_DIR/godot"

# Prepare a local NuGet source where the build will push GodotSharp (C#) packages.
mkdir -p "$LOCAL_NUGET"
# Remove any stale source definition (ignore errors if it doesn't exist).
dotnet nuget remove source MyLocalNugetSource || true
# Re-add pointing to the fresh local feed directory.
dotnet nuget add source "$DEST_DIR/nuget_local" --name MyLocalNugetSource --store-password-in-clear-text || true

# Parallel build flag for SCons (uses all available CPU cores).
JOBS="-j$(nproc)"

# Common SCons flags:
# - platform=windows      : Cross-compile Windows binaries.
# - module_mono_enabled=yes: Include Mono / C# integration.
# - use_mingw=yes         : Force MinGW (cross) toolchain.
# - precision=double      : Build engine with double precision math (must be consistent everywhere).
SCONS_BASE="platform=windows module_mono_enabled=yes use_mingw=yes precision=double"

# Flag sets for different build targets:
EDITOR_FLAGS="$SCONS_BASE"                       # Editor (development, no production stripping).
TEMPLATE_DBG_FLAGS="$SCONS_BASE target=template_debug"        # Debug export template (keeps debug hooks).
TEMPLATE_REL_FLAGS="$SCONS_BASE target=template_release production=yes" # Release export template (optimized, stripped).

# 1. First editor build WITHOUT Mono glue.
#    Rationale: The managed API glue code is generated by running a preliminary editor;
#    the engine must first compile without glue to produce the generator binary.
scons $JOBS $EDITOR_FLAGS target=editor mono_glue=no

# 2. Generate Mono glue.
#    We run the just-built double precision editor in headless mode to emit the
#    C# <-> native binding glue under modules/mono/glue. The .double. segment
#    distinguishes the precision variant in the filename; we pick the first match.
EDITOR_BIN=$(echo bin/godot.windows.editor.double*.mono.exe | awk '{print $1}')
"$EDITOR_BIN" --headless --generate-mono-glue modules/mono/glue

# 3. Rebuild the editor WITH glue.
#    Now that glue sources exist, rebuilding integrates them, enabling C# in the editor.
scons $JOBS $EDITOR_FLAGS target=editor mono_glue=yes

# 4. Build both export templates (debug & release) USING the generated glue.
#    These are the stripped runtime executables the editor embeds when exporting a project.
scons $JOBS $TEMPLATE_DBG_FLAGS mono_glue=yes
scons $JOBS $TEMPLATE_REL_FLAGS mono_glue=yes

# 5. Build C# assemblies and publish NuGet packages locally.
#    The build script compiles GodotSharp + tools assemblies matching the generated glue
#    (same platform, architecture, precision) and pushes resulting nupkgs to the local feed.
python3 modules/mono/build_scripts/build_assemblies.py \
  --godot-output-dir=./bin \
  --godot-platform=windows \
  --precision=double \
  --push-nupkgs-local "$LOCAL_NUGET"

# 6. Collect build artifacts for downstream consumption.
#    We gather: compiled binaries (bin/), local NuGet feed (packages), and glue sources
#    (useful for diagnosing or rebuilding assemblies later).
cp -r bin "$DEST_DIR/"
cp -r modules/mono/glue "$DEST_DIR/"

echo "Done. (Double precision) Artifacts are in $DEST_DIR."